- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: true

    - name: Docker login
      docker_login:
        username: "abdulmajeed951"
        password: "{{ dockerhub_password }}"
        registry: "https://index.docker.io/v1/"

    - name: Deploy Docker Container
      docker_container:
        name: finance-me-banking-container
        image: abdulmajeed951/finance-me-banking:latest
        state: started
        restart_policy: always
        published_ports:
          - "8088:8081"
